/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FundsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class FundsApiTests
    {
        private FundsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new FundsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FundsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' FundsApi
            //Assert.IsInstanceOfType(typeof(FundsApi), instance, "instance is a FundsApi");
        }

        
        /// <summary>
        /// Test FundsAdd
        /// </summary>
        [Test]
        public void FundsAddTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? investor = null;
            //ScheduledTransfer request = null;
            //var response = instance.FundsAdd(investor, request);
            //Assert.IsInstanceOf<ScheduledTransfer> (response, "response is ScheduledTransfer");
        }
        
        /// <summary>
        /// Test FundsCancel
        /// </summary>
        [Test]
        public void FundsCancelTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? investor = null;
            //CancelTransferRequest request = null;
            //var response = instance.FundsCancel(investor, request);
            //Assert.IsInstanceOf<CancelTransferResponse> (response, "response is CancelTransferResponse");
        }
        
        /// <summary>
        /// Test FundsPending
        /// </summary>
        [Test]
        public void FundsPendingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? investor = null;
            //var response = instance.FundsPending(investor);
            //Assert.IsInstanceOf<Transfers> (response, "response is Transfers");
        }
        
        /// <summary>
        /// Test FundsWithdraw
        /// </summary>
        [Test]
        public void FundsWithdrawTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? investor = null;
            //ScheduledTransfer request = null;
            //var response = instance.FundsWithdraw(investor, request);
            //Assert.IsInstanceOf<ScheduledTransfer> (response, "response is ScheduledTransfer");
        }
        
    }

}
