/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LoansApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class LoansApiTests
    {
        private LoansApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new LoansApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LoansApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' LoansApi
            //Assert.IsInstanceOfType(typeof(LoansApi), instance, "instance is a LoansApi");
        }

        
        /// <summary>
        /// Test ListedLoans
        /// </summary>
        [Test]
        public void ListedLoansTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? filterId = null;
            //bool? showAll = null;
            //string X_LC_LISTING_VERSION = null;
            //var response = instance.ListedLoans(filterId, showAll, X_LC_LISTING_VERSION);
            //Assert.IsInstanceOf<ListedLoans> (response, "response is ListedLoans");
        }
        
    }

}
