/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines CreditTrend
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CreditTrend
    {
        
        /// <summary>
        /// Enum UP for "UP"
        /// </summary>
        [EnumMember(Value = "UP")]
        UP = 1,
        
        /// <summary>
        /// Enum FLAT for "FLAT"
        /// </summary>
        [EnumMember(Value = "FLAT")]
        FLAT = 2,
        
        /// <summary>
        /// Enum DOWN for "DOWN"
        /// </summary>
        [EnumMember(Value = "DOWN")]
        DOWN = 3
    }

}
