/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// DetailedNotesOwned
    /// </summary>
    [DataContract]
    public partial class DetailedNotesOwned :  IEquatable<DetailedNotesOwned>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DetailedNotesOwned" /> class.
        /// </summary>
        /// <param name="MyNotes">MyNotes.</param>
        public DetailedNotesOwned(List<DetailedNote> MyNotes = default(List<DetailedNote>))
        {
            this.MyNotes = MyNotes;
        }
        
        /// <summary>
        /// Gets or Sets MyNotes
        /// </summary>
        [DataMember(Name="myNotes", EmitDefaultValue=false)]
        public List<DetailedNote> MyNotes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DetailedNotesOwned {\n");
            sb.Append("  MyNotes: ").Append(MyNotes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DetailedNotesOwned);
        }

        /// <summary>
        /// Returns true if DetailedNotesOwned instances are equal
        /// </summary>
        /// <param name="input">Instance of DetailedNotesOwned to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DetailedNotesOwned input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.MyNotes == input.MyNotes ||
                    this.MyNotes != null &&
                    this.MyNotes.SequenceEqual(input.MyNotes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MyNotes != null)
                    hashCode = hashCode * 59 + this.MyNotes.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
