/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines HomeOwnership
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum HomeOwnership
    {
        
        /// <summary>
        /// Enum RENT for "RENT"
        /// </summary>
        [EnumMember(Value = "RENT")]
        RENT = 1,
        
        /// <summary>
        /// Enum OWN for "OWN"
        /// </summary>
        [EnumMember(Value = "OWN")]
        OWN = 2,
        
        /// <summary>
        /// Enum MORTGAGE for "MORTGAGE"
        /// </summary>
        [EnumMember(Value = "MORTGAGE")]
        MORTGAGE = 3,
        
        /// <summary>
        /// Enum OTHER for "OTHER"
        /// </summary>
        [EnumMember(Value = "OTHER")]
        OTHER = 4
    }

}
