/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines IncomeVerified
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum IncomeVerified
    {
        
        /// <summary>
        /// Enum NOTVERIFIED for "NOT_VERIFIED"
        /// </summary>
        [EnumMember(Value = "NOT_VERIFIED")]
        NOTVERIFIED = 1,
        
        /// <summary>
        /// Enum SOURCEVERIFIED for "SOURCE_VERIFIED"
        /// </summary>
        [EnumMember(Value = "SOURCE_VERIFIED")]
        SOURCEVERIFIED = 2,
        
        /// <summary>
        /// Enum VERIFIED for "VERIFIED"
        /// </summary>
        [EnumMember(Value = "VERIFIED")]
        VERIFIED = 3
    }

}
