/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines LoanGrade
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum LoanGrade
    {
        
        /// <summary>
        /// Enum A for "A"
        /// </summary>
        [EnumMember(Value = "A")]
        A = 1,
        
        /// <summary>
        /// Enum B for "B"
        /// </summary>
        [EnumMember(Value = "B")]
        B = 2,
        
        /// <summary>
        /// Enum C for "C"
        /// </summary>
        [EnumMember(Value = "C")]
        C = 3,
        
        /// <summary>
        /// Enum D for "D"
        /// </summary>
        [EnumMember(Value = "D")]
        D = 4,
        
        /// <summary>
        /// Enum E for "E"
        /// </summary>
        [EnumMember(Value = "E")]
        E = 5,
        
        /// <summary>
        /// Enum F for "F"
        /// </summary>
        [EnumMember(Value = "F")]
        F = 6,
        
        /// <summary>
        /// Enum G for "G"
        /// </summary>
        [EnumMember(Value = "G")]
        G = 7,
        
        /// <summary>
        /// Enum A1 for "A1"
        /// </summary>
        [EnumMember(Value = "A1")]
        A1 = 8,
        
        /// <summary>
        /// Enum A2 for "A2"
        /// </summary>
        [EnumMember(Value = "A2")]
        A2 = 9,
        
        /// <summary>
        /// Enum A3 for "A3"
        /// </summary>
        [EnumMember(Value = "A3")]
        A3 = 10,
        
        /// <summary>
        /// Enum A4 for "A4"
        /// </summary>
        [EnumMember(Value = "A4")]
        A4 = 11,
        
        /// <summary>
        /// Enum A5 for "A5"
        /// </summary>
        [EnumMember(Value = "A5")]
        A5 = 12,
        
        /// <summary>
        /// Enum B1 for "B1"
        /// </summary>
        [EnumMember(Value = "B1")]
        B1 = 13,
        
        /// <summary>
        /// Enum B2 for "B2"
        /// </summary>
        [EnumMember(Value = "B2")]
        B2 = 14,
        
        /// <summary>
        /// Enum B3 for "B3"
        /// </summary>
        [EnumMember(Value = "B3")]
        B3 = 15,
        
        /// <summary>
        /// Enum B4 for "B4"
        /// </summary>
        [EnumMember(Value = "B4")]
        B4 = 16,
        
        /// <summary>
        /// Enum B5 for "B5"
        /// </summary>
        [EnumMember(Value = "B5")]
        B5 = 17,
        
        /// <summary>
        /// Enum C1 for "C1"
        /// </summary>
        [EnumMember(Value = "C1")]
        C1 = 18,
        
        /// <summary>
        /// Enum C2 for "C2"
        /// </summary>
        [EnumMember(Value = "C2")]
        C2 = 19,
        
        /// <summary>
        /// Enum C3 for "C3"
        /// </summary>
        [EnumMember(Value = "C3")]
        C3 = 20,
        
        /// <summary>
        /// Enum C4 for "C4"
        /// </summary>
        [EnumMember(Value = "C4")]
        C4 = 21,
        
        /// <summary>
        /// Enum C5 for "C5"
        /// </summary>
        [EnumMember(Value = "C5")]
        C5 = 22,
        
        /// <summary>
        /// Enum D1 for "D1"
        /// </summary>
        [EnumMember(Value = "D1")]
        D1 = 23,
        
        /// <summary>
        /// Enum D2 for "D2"
        /// </summary>
        [EnumMember(Value = "D2")]
        D2 = 24,
        
        /// <summary>
        /// Enum D3 for "D3"
        /// </summary>
        [EnumMember(Value = "D3")]
        D3 = 25,
        
        /// <summary>
        /// Enum D4 for "D4"
        /// </summary>
        [EnumMember(Value = "D4")]
        D4 = 26,
        
        /// <summary>
        /// Enum D5 for "D5"
        /// </summary>
        [EnumMember(Value = "D5")]
        D5 = 27,
        
        /// <summary>
        /// Enum E1 for "E1"
        /// </summary>
        [EnumMember(Value = "E1")]
        E1 = 28,
        
        /// <summary>
        /// Enum E2 for "E2"
        /// </summary>
        [EnumMember(Value = "E2")]
        E2 = 29,
        
        /// <summary>
        /// Enum E3 for "E3"
        /// </summary>
        [EnumMember(Value = "E3")]
        E3 = 30,
        
        /// <summary>
        /// Enum E4 for "E4"
        /// </summary>
        [EnumMember(Value = "E4")]
        E4 = 31,
        
        /// <summary>
        /// Enum E5 for "E5"
        /// </summary>
        [EnumMember(Value = "E5")]
        E5 = 32,
        
        /// <summary>
        /// Enum G1 for "G1"
        /// </summary>
        [EnumMember(Value = "G1")]
        G1 = 33,
        
        /// <summary>
        /// Enum G2 for "G2"
        /// </summary>
        [EnumMember(Value = "G2")]
        G2 = 34,
        
        /// <summary>
        /// Enum G3 for "G3"
        /// </summary>
        [EnumMember(Value = "G3")]
        G3 = 35,
        
        /// <summary>
        /// Enum G4 for "G4"
        /// </summary>
        [EnumMember(Value = "G4")]
        G4 = 36,
        
        /// <summary>
        /// Enum G5 for "G5"
        /// </summary>
        [EnumMember(Value = "G5")]
        G5 = 37
    }

}
