/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines PaymentStatus
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PaymentStatus
    {
        
        /// <summary>
        /// Enum Scheduled for "Scheduled"
        /// </summary>
        [EnumMember(Value = "Scheduled")]
        Scheduled = 1,
        
        /// <summary>
        /// Enum Processing for "Processing..."
        /// </summary>
        [EnumMember(Value = "Processing...")]
        Processing = 2,
        
        /// <summary>
        /// Enum Completed for "Completed"
        /// </summary>
        [EnumMember(Value = "Completed")]
        Completed = 3,
        
        /// <summary>
        /// Enum Overdue for "Overdue"
        /// </summary>
        [EnumMember(Value = "Overdue")]
        Overdue = 4,
        
        /// <summary>
        /// Enum PaidOff for "Paid Off"
        /// </summary>
        [EnumMember(Value = "Paid Off")]
        PaidOff = 5,
        
        /// <summary>
        /// Enum ChargedOff for "ChargedOff"
        /// </summary>
        [EnumMember(Value = "ChargedOff")]
        ChargedOff = 6
    }

}
