/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines Purpose
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Purpose
    {
        
        /// <summary>
        /// Enum Debtconsolidation for "debt_consolidation"
        /// </summary>
        [EnumMember(Value = "debt_consolidation")]
        Debtconsolidation = 1,
        
        /// <summary>
        /// Enum Medical for "medical"
        /// </summary>
        [EnumMember(Value = "medical")]
        Medical = 2,
        
        /// <summary>
        /// Enum Homeimprovement for "home_improvement"
        /// </summary>
        [EnumMember(Value = "home_improvement")]
        Homeimprovement = 3,
        
        /// <summary>
        /// Enum Renewableenergy for "renewable_energy"
        /// </summary>
        [EnumMember(Value = "renewable_energy")]
        Renewableenergy = 4,
        
        /// <summary>
        /// Enum Smallbusiness for "small_business"
        /// </summary>
        [EnumMember(Value = "small_business")]
        Smallbusiness = 5,
        
        /// <summary>
        /// Enum Wedding for "wedding"
        /// </summary>
        [EnumMember(Value = "wedding")]
        Wedding = 6,
        
        /// <summary>
        /// Enum Vacation for "vacation"
        /// </summary>
        [EnumMember(Value = "vacation")]
        Vacation = 7,
        
        /// <summary>
        /// Enum Moving for "moving"
        /// </summary>
        [EnumMember(Value = "moving")]
        Moving = 8,
        
        /// <summary>
        /// Enum House for "house"
        /// </summary>
        [EnumMember(Value = "house")]
        House = 9,
        
        /// <summary>
        /// Enum Car for "car"
        /// </summary>
        [EnumMember(Value = "car")]
        Car = 10,
        
        /// <summary>
        /// Enum Majorpurchase for "major_purchase"
        /// </summary>
        [EnumMember(Value = "major_purchase")]
        Majorpurchase = 11,
        
        /// <summary>
        /// Enum Creditcard for "credit_card"
        /// </summary>
        [EnumMember(Value = "credit_card")]
        Creditcard = 12,
        
        /// <summary>
        /// Enum Other for "other"
        /// </summary>
        [EnumMember(Value = "other")]
        Other = 13
    }

}
