/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// SellNote
    /// </summary>
    [DataContract]
    public partial class SellNote :  IEquatable<SellNote>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SellNote" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SellNote() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SellNote" /> class.
        /// </summary>
        /// <param name="LoanId">LoanId (required).</param>
        /// <param name="OrderId">OrderId (required).</param>
        /// <param name="NoteId">NoteId (required).</param>
        /// <param name="AskingPrice">AskingPrice (required).</param>
        /// <param name="ExecutionStatus">ExecutionStatus.</param>
        public SellNote(int? LoanId = default(int?), int? OrderId = default(int?), int? NoteId = default(int?), decimal? AskingPrice = default(decimal?), List<SellNoteExecutionStatus> ExecutionStatus = default(List<SellNoteExecutionStatus>))
        {
            // to ensure "LoanId" is required (not null)
            if (LoanId == null)
            {
                throw new InvalidDataException("LoanId is a required property for SellNote and cannot be null");
            }
            else
            {
                this.LoanId = LoanId;
            }
            // to ensure "OrderId" is required (not null)
            if (OrderId == null)
            {
                throw new InvalidDataException("OrderId is a required property for SellNote and cannot be null");
            }
            else
            {
                this.OrderId = OrderId;
            }
            // to ensure "NoteId" is required (not null)
            if (NoteId == null)
            {
                throw new InvalidDataException("NoteId is a required property for SellNote and cannot be null");
            }
            else
            {
                this.NoteId = NoteId;
            }
            // to ensure "AskingPrice" is required (not null)
            if (AskingPrice == null)
            {
                throw new InvalidDataException("AskingPrice is a required property for SellNote and cannot be null");
            }
            else
            {
                this.AskingPrice = AskingPrice;
            }
            this.ExecutionStatus = ExecutionStatus;
        }
        
        /// <summary>
        /// Gets or Sets LoanId
        /// </summary>
        [DataMember(Name="loanId", EmitDefaultValue=false)]
        public int? LoanId { get; set; }

        /// <summary>
        /// Gets or Sets OrderId
        /// </summary>
        [DataMember(Name="orderId", EmitDefaultValue=false)]
        public int? OrderId { get; set; }

        /// <summary>
        /// Gets or Sets NoteId
        /// </summary>
        [DataMember(Name="noteId", EmitDefaultValue=false)]
        public int? NoteId { get; set; }

        /// <summary>
        /// Gets or Sets AskingPrice
        /// </summary>
        [DataMember(Name="askingPrice", EmitDefaultValue=false)]
        public decimal? AskingPrice { get; set; }

        /// <summary>
        /// Gets or Sets ExecutionStatus
        /// </summary>
        [DataMember(Name="executionStatus", EmitDefaultValue=false)]
        public List<SellNoteExecutionStatus> ExecutionStatus { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SellNote {\n");
            sb.Append("  LoanId: ").Append(LoanId).Append("\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("  NoteId: ").Append(NoteId).Append("\n");
            sb.Append("  AskingPrice: ").Append(AskingPrice).Append("\n");
            sb.Append("  ExecutionStatus: ").Append(ExecutionStatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SellNote);
        }

        /// <summary>
        /// Returns true if SellNote instances are equal
        /// </summary>
        /// <param name="input">Instance of SellNote to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SellNote input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.LoanId == input.LoanId ||
                    (this.LoanId != null &&
                    this.LoanId.Equals(input.LoanId))
                ) && 
                (
                    this.OrderId == input.OrderId ||
                    (this.OrderId != null &&
                    this.OrderId.Equals(input.OrderId))
                ) && 
                (
                    this.NoteId == input.NoteId ||
                    (this.NoteId != null &&
                    this.NoteId.Equals(input.NoteId))
                ) && 
                (
                    this.AskingPrice == input.AskingPrice ||
                    (this.AskingPrice != null &&
                    this.AskingPrice.Equals(input.AskingPrice))
                ) && 
                (
                    this.ExecutionStatus == input.ExecutionStatus ||
                    this.ExecutionStatus != null &&
                    this.ExecutionStatus.SequenceEqual(input.ExecutionStatus)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.LoanId != null)
                    hashCode = hashCode * 59 + this.LoanId.GetHashCode();
                if (this.OrderId != null)
                    hashCode = hashCode * 59 + this.OrderId.GetHashCode();
                if (this.NoteId != null)
                    hashCode = hashCode * 59 + this.NoteId.GetHashCode();
                if (this.AskingPrice != null)
                    hashCode = hashCode * 59 + this.AskingPrice.GetHashCode();
                if (this.ExecutionStatus != null)
                    hashCode = hashCode * 59 + this.ExecutionStatus.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
