/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// SubmitOrderResponse
    /// </summary>
    [DataContract]
    public partial class SubmitOrderResponse :  IEquatable<SubmitOrderResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SubmitOrderResponse" /> class.
        /// </summary>
        /// <param name="OrderInstructId">OrderInstructId.</param>
        /// <param name="OrderConfirmations">OrderConfirmations.</param>
        public SubmitOrderResponse(int? OrderInstructId = default(int?), List<OrderStatus> OrderConfirmations = default(List<OrderStatus>))
        {
            this.OrderInstructId = OrderInstructId;
            this.OrderConfirmations = OrderConfirmations;
        }
        
        /// <summary>
        /// Gets or Sets OrderInstructId
        /// </summary>
        [DataMember(Name="orderInstructId", EmitDefaultValue=false)]
        public int? OrderInstructId { get; set; }

        /// <summary>
        /// Gets or Sets OrderConfirmations
        /// </summary>
        [DataMember(Name="orderConfirmations", EmitDefaultValue=false)]
        public List<OrderStatus> OrderConfirmations { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SubmitOrderResponse {\n");
            sb.Append("  OrderInstructId: ").Append(OrderInstructId).Append("\n");
            sb.Append("  OrderConfirmations: ").Append(OrderConfirmations).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SubmitOrderResponse);
        }

        /// <summary>
        /// Returns true if SubmitOrderResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of SubmitOrderResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SubmitOrderResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.OrderInstructId == input.OrderInstructId ||
                    (this.OrderInstructId != null &&
                    this.OrderInstructId.Equals(input.OrderInstructId))
                ) && 
                (
                    this.OrderConfirmations == input.OrderConfirmations ||
                    this.OrderConfirmations != null &&
                    this.OrderConfirmations.SequenceEqual(input.OrderConfirmations)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OrderInstructId != null)
                    hashCode = hashCode * 59 + this.OrderInstructId.GetHashCode();
                if (this.OrderConfirmations != null)
                    hashCode = hashCode * 59 + this.OrderConfirmations.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
