/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Transfers
    /// </summary>
    [DataContract]
    public partial class Transfers :  IEquatable<Transfers>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Transfers" /> class.
        /// </summary>
        /// <param name="_Transfers">_Transfers.</param>
        public Transfers(List<Transfer> _Transfers = default(List<Transfer>))
        {
            this._Transfers = _Transfers;
        }
        
        /// <summary>
        /// Gets or Sets _Transfers
        /// </summary>
        [DataMember(Name="transfers", EmitDefaultValue=false)]
        public List<Transfer> _Transfers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Transfers {\n");
            sb.Append("  _Transfers: ").Append(_Transfers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Transfers);
        }

        /// <summary>
        /// Returns true if Transfers instances are equal
        /// </summary>
        /// <param name="input">Instance of Transfers to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Transfers input)
        {
            if (input == null)
                return false;

            return 
                (
                    this._Transfers == input._Transfers ||
                    this._Transfers != null &&
                    this._Transfers.SequenceEqual(input._Transfers)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this._Transfers != null)
                    hashCode = hashCode * 59 + this._Transfers.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
