/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Frequency of transfer
    /// </summary>
    /// <value>Frequency of transfer</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TransferFrequency
    {
        
        /// <summary>
        /// Enum NOW for "LOAD_NOW"
        /// </summary>
        [EnumMember(Value = "LOAD_NOW")]
        NOW = 1,
        
        /// <summary>
        /// Enum ONCE for "LOAD_ONCE"
        /// </summary>
        [EnumMember(Value = "LOAD_ONCE")]
        ONCE = 2,
        
        /// <summary>
        /// Enum WEEKLY for "LOAD_WEEKLY"
        /// </summary>
        [EnumMember(Value = "LOAD_WEEKLY")]
        WEEKLY = 3,
        
        /// <summary>
        /// Enum BIWEEKLY for "LOAD_BIWEEKLY"
        /// </summary>
        [EnumMember(Value = "LOAD_BIWEEKLY")]
        BIWEEKLY = 4,
        
        /// <summary>
        /// Enum ONDAY1AND16 for "LOAD_ON_DAY_1_AND_16"
        /// </summary>
        [EnumMember(Value = "LOAD_ON_DAY_1_AND_16")]
        ONDAY1AND16 = 5,
        
        /// <summary>
        /// Enum MONTHLY for "LOAD_MONTHLY"
        /// </summary>
        [EnumMember(Value = "LOAD_MONTHLY")]
        MONTHLY = 6
    }

}
