/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AccountSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AccountSummaryTests
    {
        // TODO uncomment below to declare an instance variable for AccountSummary
        //private AccountSummary instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AccountSummary
            //instance = new AccountSummary();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccountSummary
        /// </summary>
        [Test]
        public void AccountSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AccountSummary
            //Assert.IsInstanceOfType<AccountSummary> (instance, "variable 'instance' is a AccountSummary");
        }


        /// <summary>
        /// Test the property 'AvailableCash'
        /// </summary>
        [Test]
        public void AvailableCashTest()
        {
            // TODO unit test for the property 'AvailableCash'
        }
        /// <summary>
        /// Test the property 'InvestorId'
        /// </summary>
        [Test]
        public void InvestorIdTest()
        {
            // TODO unit test for the property 'InvestorId'
        }
        /// <summary>
        /// Test the property 'AccruedInterest'
        /// </summary>
        [Test]
        public void AccruedInterestTest()
        {
            // TODO unit test for the property 'AccruedInterest'
        }
        /// <summary>
        /// Test the property 'OutstandingPrincipal'
        /// </summary>
        [Test]
        public void OutstandingPrincipalTest()
        {
            // TODO unit test for the property 'OutstandingPrincipal'
        }
        /// <summary>
        /// Test the property 'AccountTotal'
        /// </summary>
        [Test]
        public void AccountTotalTest()
        {
            // TODO unit test for the property 'AccountTotal'
        }
        /// <summary>
        /// Test the property 'TotalNotes'
        /// </summary>
        [Test]
        public void TotalNotesTest()
        {
            // TODO unit test for the property 'TotalNotes'
        }
        /// <summary>
        /// Test the property 'TotalPortfolios'
        /// </summary>
        [Test]
        public void TotalPortfoliosTest()
        {
            // TODO unit test for the property 'TotalPortfolios'
        }
        /// <summary>
        /// Test the property 'InFundingBalance'
        /// </summary>
        [Test]
        public void InFundingBalanceTest()
        {
            // TODO unit test for the property 'InFundingBalance'
        }
        /// <summary>
        /// Test the property 'ReceivedInterest'
        /// </summary>
        [Test]
        public void ReceivedInterestTest()
        {
            // TODO unit test for the property 'ReceivedInterest'
        }
        /// <summary>
        /// Test the property 'ReceivedPrincipal'
        /// </summary>
        [Test]
        public void ReceivedPrincipalTest()
        {
            // TODO unit test for the property 'ReceivedPrincipal'
        }
        /// <summary>
        /// Test the property 'ReceivedLateFees'
        /// </summary>
        [Test]
        public void ReceivedLateFeesTest()
        {
            // TODO unit test for the property 'ReceivedLateFees'
        }
        /// <summary>
        /// Test the property 'NetAnnualizedReturn'
        /// </summary>
        [Test]
        public void NetAnnualizedReturnTest()
        {
            // TODO unit test for the property 'NetAnnualizedReturn'
        }
        /// <summary>
        /// Test the property 'Adjustments'
        /// </summary>
        [Test]
        public void AdjustmentsTest()
        {
            // TODO unit test for the property 'Adjustments'
        }

    }

}
