/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AvailableCash
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AvailableCashTests
    {
        // TODO uncomment below to declare an instance variable for AvailableCash
        //private AvailableCash instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AvailableCash
            //instance = new AvailableCash();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AvailableCash
        /// </summary>
        [Test]
        public void AvailableCashInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AvailableCash
            //Assert.IsInstanceOfType<AvailableCash> (instance, "variable 'instance' is a AvailableCash");
        }


        /// <summary>
        /// Test the property 'InvestorId'
        /// </summary>
        [Test]
        public void InvestorIdTest()
        {
            // TODO unit test for the property 'InvestorId'
        }
        /// <summary>
        /// Test the property '_AvailableCash'
        /// </summary>
        [Test]
        public void _AvailableCashTest()
        {
            // TODO unit test for the property '_AvailableCash'
        }

    }

}
