/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BuyNotesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BuyNotesResponseTests
    {
        // TODO uncomment below to declare an instance variable for BuyNotesResponse
        //private BuyNotesResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BuyNotesResponse
            //instance = new BuyNotesResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BuyNotesResponse
        /// </summary>
        [Test]
        public void BuyNotesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BuyNotesResponse
            //Assert.IsInstanceOfType<BuyNotesResponse> (instance, "variable 'instance' is a BuyNotesResponse");
        }


        /// <summary>
        /// Test the property 'BuyNoteConfirmations'
        /// </summary>
        [Test]
        public void BuyNoteConfirmationsTest()
        {
            // TODO unit test for the property 'BuyNoteConfirmations'
        }

    }

}
