/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BuyNote
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BuyNoteTests
    {
        // TODO uncomment below to declare an instance variable for BuyNote
        //private BuyNote instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BuyNote
            //instance = new BuyNote();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BuyNote
        /// </summary>
        [Test]
        public void BuyNoteInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BuyNote
            //Assert.IsInstanceOfType<BuyNote> (instance, "variable 'instance' is a BuyNote");
        }


        /// <summary>
        /// Test the property 'LoanId'
        /// </summary>
        [Test]
        public void LoanIdTest()
        {
            // TODO unit test for the property 'LoanId'
        }
        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Test]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }
        /// <summary>
        /// Test the property 'NoteId'
        /// </summary>
        [Test]
        public void NoteIdTest()
        {
            // TODO unit test for the property 'NoteId'
        }
        /// <summary>
        /// Test the property 'BidPrice'
        /// </summary>
        [Test]
        public void BidPriceTest()
        {
            // TODO unit test for the property 'BidPrice'
        }
        /// <summary>
        /// Test the property 'OutstandingAccruedInterest'
        /// </summary>
        [Test]
        public void OutstandingAccruedInterestTest()
        {
            // TODO unit test for the property 'OutstandingAccruedInterest'
        }
        /// <summary>
        /// Test the property 'OutstandingPrincipal'
        /// </summary>
        [Test]
        public void OutstandingPrincipalTest()
        {
            // TODO unit test for the property 'OutstandingPrincipal'
        }
        /// <summary>
        /// Test the property 'YieldToMaturity'
        /// </summary>
        [Test]
        public void YieldToMaturityTest()
        {
            // TODO unit test for the property 'YieldToMaturity'
        }
        /// <summary>
        /// Test the property 'ExecutionStatus'
        /// </summary>
        [Test]
        public void ExecutionStatusTest()
        {
            // TODO unit test for the property 'ExecutionStatus'
        }

    }

}
