/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BuyNotesRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BuyNotesRequestTests
    {
        // TODO uncomment below to declare an instance variable for BuyNotesRequest
        //private BuyNotesRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BuyNotesRequest
            //instance = new BuyNotesRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BuyNotesRequest
        /// </summary>
        [Test]
        public void BuyNotesRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BuyNotesRequest
            //Assert.IsInstanceOfType<BuyNotesRequest> (instance, "variable 'instance' is a BuyNotesRequest");
        }


        /// <summary>
        /// Test the property 'Aid'
        /// </summary>
        [Test]
        public void AidTest()
        {
            // TODO unit test for the property 'Aid'
        }
        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Test]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }

    }

}
