/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CancelTransferResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CancelTransferResponseTests
    {
        // TODO uncomment below to declare an instance variable for CancelTransferResponse
        //private CancelTransferResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CancelTransferResponse
            //instance = new CancelTransferResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CancelTransferResponse
        /// </summary>
        [Test]
        public void CancelTransferResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CancelTransferResponse
            //Assert.IsInstanceOfType<CancelTransferResponse> (instance, "variable 'instance' is a CancelTransferResponse");
        }


        /// <summary>
        /// Test the property 'InvestorId'
        /// </summary>
        [Test]
        public void InvestorIdTest()
        {
            // TODO unit test for the property 'InvestorId'
        }
        /// <summary>
        /// Test the property 'CancellationResults'
        /// </summary>
        [Test]
        public void CancellationResultsTest()
        {
            // TODO unit test for the property 'CancellationResults'
        }

    }

}
