/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CreatePortfolioRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreatePortfolioRequestTests
    {
        // TODO uncomment below to declare an instance variable for CreatePortfolioRequest
        //private CreatePortfolioRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreatePortfolioRequest
            //instance = new CreatePortfolioRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreatePortfolioRequest
        /// </summary>
        [Test]
        public void CreatePortfolioRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreatePortfolioRequest
            //Assert.IsInstanceOfType<CreatePortfolioRequest> (instance, "variable 'instance' is a CreatePortfolioRequest");
        }


        /// <summary>
        /// Test the property 'ActorId'
        /// </summary>
        [Test]
        public void ActorIdTest()
        {
            // TODO unit test for the property 'ActorId'
        }
        /// <summary>
        /// Test the property 'PortfolioName'
        /// </summary>
        [Test]
        public void PortfolioNameTest()
        {
            // TODO unit test for the property 'PortfolioName'
        }
        /// <summary>
        /// Test the property 'PortfolioDescription'
        /// </summary>
        [Test]
        public void PortfolioDescriptionTest()
        {
            // TODO unit test for the property 'PortfolioDescription'
        }

    }

}
