/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DetailedNote
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DetailedNoteTests
    {
        // TODO uncomment below to declare an instance variable for DetailedNote
        //private DetailedNote instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DetailedNote
            //instance = new DetailedNote();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DetailedNote
        /// </summary>
        [Test]
        public void DetailedNoteInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DetailedNote
            //Assert.IsInstanceOfType<DetailedNote> (instance, "variable 'instance' is a DetailedNote");
        }


        /// <summary>
        /// Test the property 'LoanId'
        /// </summary>
        [Test]
        public void LoanIdTest()
        {
            // TODO unit test for the property 'LoanId'
        }
        /// <summary>
        /// Test the property 'NoteId'
        /// </summary>
        [Test]
        public void NoteIdTest()
        {
            // TODO unit test for the property 'NoteId'
        }
        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Test]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }
        /// <summary>
        /// Test the property 'InterestRate'
        /// </summary>
        [Test]
        public void InterestRateTest()
        {
            // TODO unit test for the property 'InterestRate'
        }
        /// <summary>
        /// Test the property 'LoanLength'
        /// </summary>
        [Test]
        public void LoanLengthTest()
        {
            // TODO unit test for the property 'LoanLength'
        }
        /// <summary>
        /// Test the property 'LoanStatus'
        /// </summary>
        [Test]
        public void LoanStatusTest()
        {
            // TODO unit test for the property 'LoanStatus'
        }
        /// <summary>
        /// Test the property 'Grade'
        /// </summary>
        [Test]
        public void GradeTest()
        {
            // TODO unit test for the property 'Grade'
        }
        /// <summary>
        /// Test the property 'LoanAmount'
        /// </summary>
        [Test]
        public void LoanAmountTest()
        {
            // TODO unit test for the property 'LoanAmount'
        }
        /// <summary>
        /// Test the property 'NoteAmount'
        /// </summary>
        [Test]
        public void NoteAmountTest()
        {
            // TODO unit test for the property 'NoteAmount'
        }
        /// <summary>
        /// Test the property 'PaymentsReceived'
        /// </summary>
        [Test]
        public void PaymentsReceivedTest()
        {
            // TODO unit test for the property 'PaymentsReceived'
        }
        /// <summary>
        /// Test the property 'IssueDate'
        /// </summary>
        [Test]
        public void IssueDateTest()
        {
            // TODO unit test for the property 'IssueDate'
        }
        /// <summary>
        /// Test the property 'OrderDate'
        /// </summary>
        [Test]
        public void OrderDateTest()
        {
            // TODO unit test for the property 'OrderDate'
        }
        /// <summary>
        /// Test the property 'LoanStatusDate'
        /// </summary>
        [Test]
        public void LoanStatusDateTest()
        {
            // TODO unit test for the property 'LoanStatusDate'
        }
        /// <summary>
        /// Test the property 'Purpose'
        /// </summary>
        [Test]
        public void PurposeTest()
        {
            // TODO unit test for the property 'Purpose'
        }
        /// <summary>
        /// Test the property 'CurrentPaymentStatus'
        /// </summary>
        [Test]
        public void CurrentPaymentStatusTest()
        {
            // TODO unit test for the property 'CurrentPaymentStatus'
        }
        /// <summary>
        /// Test the property 'CanBeTraded'
        /// </summary>
        [Test]
        public void CanBeTradedTest()
        {
            // TODO unit test for the property 'CanBeTraded'
        }
        /// <summary>
        /// Test the property 'CreditTrend'
        /// </summary>
        [Test]
        public void CreditTrendTest()
        {
            // TODO unit test for the property 'CreditTrend'
        }
        /// <summary>
        /// Test the property 'AccruedInterest'
        /// </summary>
        [Test]
        public void AccruedInterestTest()
        {
            // TODO unit test for the property 'AccruedInterest'
        }
        /// <summary>
        /// Test the property 'PrincipalPending'
        /// </summary>
        [Test]
        public void PrincipalPendingTest()
        {
            // TODO unit test for the property 'PrincipalPending'
        }
        /// <summary>
        /// Test the property 'InterestPending'
        /// </summary>
        [Test]
        public void InterestPendingTest()
        {
            // TODO unit test for the property 'InterestPending'
        }
        /// <summary>
        /// Test the property 'PrincipalReceived'
        /// </summary>
        [Test]
        public void PrincipalReceivedTest()
        {
            // TODO unit test for the property 'PrincipalReceived'
        }
        /// <summary>
        /// Test the property 'InterestReceived'
        /// </summary>
        [Test]
        public void InterestReceivedTest()
        {
            // TODO unit test for the property 'InterestReceived'
        }
        /// <summary>
        /// Test the property 'ApplicationType'
        /// </summary>
        [Test]
        public void ApplicationTypeTest()
        {
            // TODO unit test for the property 'ApplicationType'
        }
        /// <summary>
        /// Test the property 'DisbursementMethod'
        /// </summary>
        [Test]
        public void DisbursementMethodTest()
        {
            // TODO unit test for the property 'DisbursementMethod'
        }

    }

}
