/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ExecutionStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExecutionStatusTests
    {
        // TODO uncomment below to declare an instance variable for ExecutionStatus
        //private ExecutionStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExecutionStatus
            //instance = new ExecutionStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExecutionStatus
        /// </summary>
        [Test]
        public void ExecutionStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExecutionStatus
            //Assert.IsInstanceOfType<ExecutionStatus> (instance, "variable 'instance' is a ExecutionStatus");
        }



    }

}
