/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ListedLoan
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ListedLoanTests
    {
        // TODO uncomment below to declare an instance variable for ListedLoan
        //private ListedLoan instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ListedLoan
            //instance = new ListedLoan();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ListedLoan
        /// </summary>
        [Test]
        public void ListedLoanInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ListedLoan
            //Assert.IsInstanceOfType<ListedLoan> (instance, "variable 'instance' is a ListedLoan");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'MemberId'
        /// </summary>
        [Test]
        public void MemberIdTest()
        {
            // TODO unit test for the property 'MemberId'
        }
        /// <summary>
        /// Test the property 'LoanAmount'
        /// </summary>
        [Test]
        public void LoanAmountTest()
        {
            // TODO unit test for the property 'LoanAmount'
        }
        /// <summary>
        /// Test the property 'FundedAmount'
        /// </summary>
        [Test]
        public void FundedAmountTest()
        {
            // TODO unit test for the property 'FundedAmount'
        }
        /// <summary>
        /// Test the property 'Term'
        /// </summary>
        [Test]
        public void TermTest()
        {
            // TODO unit test for the property 'Term'
        }
        /// <summary>
        /// Test the property 'IntRate'
        /// </summary>
        [Test]
        public void IntRateTest()
        {
            // TODO unit test for the property 'IntRate'
        }
        /// <summary>
        /// Test the property 'ExpDefaultRate'
        /// </summary>
        [Test]
        public void ExpDefaultRateTest()
        {
            // TODO unit test for the property 'ExpDefaultRate'
        }
        /// <summary>
        /// Test the property 'ServiceFeeRate'
        /// </summary>
        [Test]
        public void ServiceFeeRateTest()
        {
            // TODO unit test for the property 'ServiceFeeRate'
        }
        /// <summary>
        /// Test the property 'Installment'
        /// </summary>
        [Test]
        public void InstallmentTest()
        {
            // TODO unit test for the property 'Installment'
        }
        /// <summary>
        /// Test the property 'Grade'
        /// </summary>
        [Test]
        public void GradeTest()
        {
            // TODO unit test for the property 'Grade'
        }
        /// <summary>
        /// Test the property 'SubGrade'
        /// </summary>
        [Test]
        public void SubGradeTest()
        {
            // TODO unit test for the property 'SubGrade'
        }
        /// <summary>
        /// Test the property 'EmpLength'
        /// </summary>
        [Test]
        public void EmpLengthTest()
        {
            // TODO unit test for the property 'EmpLength'
        }
        /// <summary>
        /// Test the property 'HomeOwnership'
        /// </summary>
        [Test]
        public void HomeOwnershipTest()
        {
            // TODO unit test for the property 'HomeOwnership'
        }
        /// <summary>
        /// Test the property 'AnnualInc'
        /// </summary>
        [Test]
        public void AnnualIncTest()
        {
            // TODO unit test for the property 'AnnualInc'
        }
        /// <summary>
        /// Test the property 'IsIncV'
        /// </summary>
        [Test]
        public void IsIncVTest()
        {
            // TODO unit test for the property 'IsIncV'
        }
        /// <summary>
        /// Test the property 'AcceptD'
        /// </summary>
        [Test]
        public void AcceptDTest()
        {
            // TODO unit test for the property 'AcceptD'
        }
        /// <summary>
        /// Test the property 'ExpD'
        /// </summary>
        [Test]
        public void ExpDTest()
        {
            // TODO unit test for the property 'ExpD'
        }
        /// <summary>
        /// Test the property 'ListD'
        /// </summary>
        [Test]
        public void ListDTest()
        {
            // TODO unit test for the property 'ListD'
        }
        /// <summary>
        /// Test the property 'CreditPullD'
        /// </summary>
        [Test]
        public void CreditPullDTest()
        {
            // TODO unit test for the property 'CreditPullD'
        }
        /// <summary>
        /// Test the property 'ReviewStatusD'
        /// </summary>
        [Test]
        public void ReviewStatusDTest()
        {
            // TODO unit test for the property 'ReviewStatusD'
        }
        /// <summary>
        /// Test the property 'ReviewStatus'
        /// </summary>
        [Test]
        public void ReviewStatusTest()
        {
            // TODO unit test for the property 'ReviewStatus'
        }
        /// <summary>
        /// Test the property 'Desc'
        /// </summary>
        [Test]
        public void DescTest()
        {
            // TODO unit test for the property 'Desc'
        }
        /// <summary>
        /// Test the property 'Purpose'
        /// </summary>
        [Test]
        public void PurposeTest()
        {
            // TODO unit test for the property 'Purpose'
        }
        /// <summary>
        /// Test the property 'AddrZip'
        /// </summary>
        [Test]
        public void AddrZipTest()
        {
            // TODO unit test for the property 'AddrZip'
        }
        /// <summary>
        /// Test the property 'InvestorCount'
        /// </summary>
        [Test]
        public void InvestorCountTest()
        {
            // TODO unit test for the property 'InvestorCount'
        }
        /// <summary>
        /// Test the property 'IlsExpD'
        /// </summary>
        [Test]
        public void IlsExpDTest()
        {
            // TODO unit test for the property 'IlsExpD'
        }
        /// <summary>
        /// Test the property 'InitialListStatus'
        /// </summary>
        [Test]
        public void InitialListStatusTest()
        {
            // TODO unit test for the property 'InitialListStatus'
        }
        /// <summary>
        /// Test the property 'EmpTitle'
        /// </summary>
        [Test]
        public void EmpTitleTest()
        {
            // TODO unit test for the property 'EmpTitle'
        }
        /// <summary>
        /// Test the property 'AccNowDelinq'
        /// </summary>
        [Test]
        public void AccNowDelinqTest()
        {
            // TODO unit test for the property 'AccNowDelinq'
        }
        /// <summary>
        /// Test the property 'AccOpenPast24Mths'
        /// </summary>
        [Test]
        public void AccOpenPast24MthsTest()
        {
            // TODO unit test for the property 'AccOpenPast24Mths'
        }
        /// <summary>
        /// Test the property 'BcOpenToBuy'
        /// </summary>
        [Test]
        public void BcOpenToBuyTest()
        {
            // TODO unit test for the property 'BcOpenToBuy'
        }
        /// <summary>
        /// Test the property 'PercentBcGt75'
        /// </summary>
        [Test]
        public void PercentBcGt75Test()
        {
            // TODO unit test for the property 'PercentBcGt75'
        }
        /// <summary>
        /// Test the property 'BcUtil'
        /// </summary>
        [Test]
        public void BcUtilTest()
        {
            // TODO unit test for the property 'BcUtil'
        }
        /// <summary>
        /// Test the property 'Dti'
        /// </summary>
        [Test]
        public void DtiTest()
        {
            // TODO unit test for the property 'Dti'
        }
        /// <summary>
        /// Test the property 'Delinq2Yrs'
        /// </summary>
        [Test]
        public void Delinq2YrsTest()
        {
            // TODO unit test for the property 'Delinq2Yrs'
        }
        /// <summary>
        /// Test the property 'DelinqAmnt'
        /// </summary>
        [Test]
        public void DelinqAmntTest()
        {
            // TODO unit test for the property 'DelinqAmnt'
        }
        /// <summary>
        /// Test the property 'EarliestCrLine'
        /// </summary>
        [Test]
        public void EarliestCrLineTest()
        {
            // TODO unit test for the property 'EarliestCrLine'
        }
        /// <summary>
        /// Test the property 'FicoRangeLow'
        /// </summary>
        [Test]
        public void FicoRangeLowTest()
        {
            // TODO unit test for the property 'FicoRangeLow'
        }
        /// <summary>
        /// Test the property 'FicoRangeHigh'
        /// </summary>
        [Test]
        public void FicoRangeHighTest()
        {
            // TODO unit test for the property 'FicoRangeHigh'
        }
        /// <summary>
        /// Test the property 'InqLast6Mths'
        /// </summary>
        [Test]
        public void InqLast6MthsTest()
        {
            // TODO unit test for the property 'InqLast6Mths'
        }
        /// <summary>
        /// Test the property 'MthsSinceLastDelinq'
        /// </summary>
        [Test]
        public void MthsSinceLastDelinqTest()
        {
            // TODO unit test for the property 'MthsSinceLastDelinq'
        }
        /// <summary>
        /// Test the property 'MthsSinceLastRecord'
        /// </summary>
        [Test]
        public void MthsSinceLastRecordTest()
        {
            // TODO unit test for the property 'MthsSinceLastRecord'
        }
        /// <summary>
        /// Test the property 'MthsSinceRecentInq'
        /// </summary>
        [Test]
        public void MthsSinceRecentInqTest()
        {
            // TODO unit test for the property 'MthsSinceRecentInq'
        }
        /// <summary>
        /// Test the property 'MthsSinceRecentBc'
        /// </summary>
        [Test]
        public void MthsSinceRecentBcTest()
        {
            // TODO unit test for the property 'MthsSinceRecentBc'
        }
        /// <summary>
        /// Test the property 'MortAcc'
        /// </summary>
        [Test]
        public void MortAccTest()
        {
            // TODO unit test for the property 'MortAcc'
        }
        /// <summary>
        /// Test the property 'OpenAcc'
        /// </summary>
        [Test]
        public void OpenAccTest()
        {
            // TODO unit test for the property 'OpenAcc'
        }
        /// <summary>
        /// Test the property 'PubRec'
        /// </summary>
        [Test]
        public void PubRecTest()
        {
            // TODO unit test for the property 'PubRec'
        }
        /// <summary>
        /// Test the property 'TotalBalExMort'
        /// </summary>
        [Test]
        public void TotalBalExMortTest()
        {
            // TODO unit test for the property 'TotalBalExMort'
        }
        /// <summary>
        /// Test the property 'RevolBal'
        /// </summary>
        [Test]
        public void RevolBalTest()
        {
            // TODO unit test for the property 'RevolBal'
        }
        /// <summary>
        /// Test the property 'RevolUtil'
        /// </summary>
        [Test]
        public void RevolUtilTest()
        {
            // TODO unit test for the property 'RevolUtil'
        }
        /// <summary>
        /// Test the property 'TotalBcLimit'
        /// </summary>
        [Test]
        public void TotalBcLimitTest()
        {
            // TODO unit test for the property 'TotalBcLimit'
        }
        /// <summary>
        /// Test the property 'TotalAcc'
        /// </summary>
        [Test]
        public void TotalAccTest()
        {
            // TODO unit test for the property 'TotalAcc'
        }
        /// <summary>
        /// Test the property 'TotalIlHighCreditLimit'
        /// </summary>
        [Test]
        public void TotalIlHighCreditLimitTest()
        {
            // TODO unit test for the property 'TotalIlHighCreditLimit'
        }
        /// <summary>
        /// Test the property 'NumRevAccts'
        /// </summary>
        [Test]
        public void NumRevAcctsTest()
        {
            // TODO unit test for the property 'NumRevAccts'
        }
        /// <summary>
        /// Test the property 'MthsSinceRecentBcDlq'
        /// </summary>
        [Test]
        public void MthsSinceRecentBcDlqTest()
        {
            // TODO unit test for the property 'MthsSinceRecentBcDlq'
        }
        /// <summary>
        /// Test the property 'PubRecBankruptcies'
        /// </summary>
        [Test]
        public void PubRecBankruptciesTest()
        {
            // TODO unit test for the property 'PubRecBankruptcies'
        }
        /// <summary>
        /// Test the property 'NumAcctsEver120Ppd'
        /// </summary>
        [Test]
        public void NumAcctsEver120PpdTest()
        {
            // TODO unit test for the property 'NumAcctsEver120Ppd'
        }
        /// <summary>
        /// Test the property 'ChargeoffWithin12Mths'
        /// </summary>
        [Test]
        public void ChargeoffWithin12MthsTest()
        {
            // TODO unit test for the property 'ChargeoffWithin12Mths'
        }
        /// <summary>
        /// Test the property 'Collections12MthsExMed'
        /// </summary>
        [Test]
        public void Collections12MthsExMedTest()
        {
            // TODO unit test for the property 'Collections12MthsExMed'
        }
        /// <summary>
        /// Test the property 'TaxLiens'
        /// </summary>
        [Test]
        public void TaxLiensTest()
        {
            // TODO unit test for the property 'TaxLiens'
        }
        /// <summary>
        /// Test the property 'MthsSinceLastMajorDerog'
        /// </summary>
        [Test]
        public void MthsSinceLastMajorDerogTest()
        {
            // TODO unit test for the property 'MthsSinceLastMajorDerog'
        }
        /// <summary>
        /// Test the property 'NumSats'
        /// </summary>
        [Test]
        public void NumSatsTest()
        {
            // TODO unit test for the property 'NumSats'
        }
        /// <summary>
        /// Test the property 'NumTlOpPast12m'
        /// </summary>
        [Test]
        public void NumTlOpPast12mTest()
        {
            // TODO unit test for the property 'NumTlOpPast12m'
        }
        /// <summary>
        /// Test the property 'MoSinRcntTl'
        /// </summary>
        [Test]
        public void MoSinRcntTlTest()
        {
            // TODO unit test for the property 'MoSinRcntTl'
        }
        /// <summary>
        /// Test the property 'TotHiCredLim'
        /// </summary>
        [Test]
        public void TotHiCredLimTest()
        {
            // TODO unit test for the property 'TotHiCredLim'
        }
        /// <summary>
        /// Test the property 'TotCurBal'
        /// </summary>
        [Test]
        public void TotCurBalTest()
        {
            // TODO unit test for the property 'TotCurBal'
        }
        /// <summary>
        /// Test the property 'AvgCurBal'
        /// </summary>
        [Test]
        public void AvgCurBalTest()
        {
            // TODO unit test for the property 'AvgCurBal'
        }
        /// <summary>
        /// Test the property 'NumActvBcTl'
        /// </summary>
        [Test]
        public void NumActvBcTlTest()
        {
            // TODO unit test for the property 'NumActvBcTl'
        }
        /// <summary>
        /// Test the property 'NumBcSats'
        /// </summary>
        [Test]
        public void NumBcSatsTest()
        {
            // TODO unit test for the property 'NumBcSats'
        }
        /// <summary>
        /// Test the property 'PctTlNvrDlq'
        /// </summary>
        [Test]
        public void PctTlNvrDlqTest()
        {
            // TODO unit test for the property 'PctTlNvrDlq'
        }
        /// <summary>
        /// Test the property 'NumTl90gDpd24m'
        /// </summary>
        [Test]
        public void NumTl90gDpd24mTest()
        {
            // TODO unit test for the property 'NumTl90gDpd24m'
        }
        /// <summary>
        /// Test the property 'NumTl30dpd'
        /// </summary>
        [Test]
        public void NumTl30dpdTest()
        {
            // TODO unit test for the property 'NumTl30dpd'
        }
        /// <summary>
        /// Test the property 'NumTl120dpd2m'
        /// </summary>
        [Test]
        public void NumTl120dpd2mTest()
        {
            // TODO unit test for the property 'NumTl120dpd2m'
        }
        /// <summary>
        /// Test the property 'NumIlTl'
        /// </summary>
        [Test]
        public void NumIlTlTest()
        {
            // TODO unit test for the property 'NumIlTl'
        }
        /// <summary>
        /// Test the property 'MoSinOldIlAcct'
        /// </summary>
        [Test]
        public void MoSinOldIlAcctTest()
        {
            // TODO unit test for the property 'MoSinOldIlAcct'
        }
        /// <summary>
        /// Test the property 'NumActvRevTl'
        /// </summary>
        [Test]
        public void NumActvRevTlTest()
        {
            // TODO unit test for the property 'NumActvRevTl'
        }
        /// <summary>
        /// Test the property 'MoSinOldRevTlOp'
        /// </summary>
        [Test]
        public void MoSinOldRevTlOpTest()
        {
            // TODO unit test for the property 'MoSinOldRevTlOp'
        }
        /// <summary>
        /// Test the property 'MoSinRcntRevTlOp'
        /// </summary>
        [Test]
        public void MoSinRcntRevTlOpTest()
        {
            // TODO unit test for the property 'MoSinRcntRevTlOp'
        }
        /// <summary>
        /// Test the property 'TotalRevHiLim'
        /// </summary>
        [Test]
        public void TotalRevHiLimTest()
        {
            // TODO unit test for the property 'TotalRevHiLim'
        }
        /// <summary>
        /// Test the property 'NumRevTlBalGt0'
        /// </summary>
        [Test]
        public void NumRevTlBalGt0Test()
        {
            // TODO unit test for the property 'NumRevTlBalGt0'
        }
        /// <summary>
        /// Test the property 'NumOpRevTl'
        /// </summary>
        [Test]
        public void NumOpRevTlTest()
        {
            // TODO unit test for the property 'NumOpRevTl'
        }
        /// <summary>
        /// Test the property 'TotCollAmt'
        /// </summary>
        [Test]
        public void TotCollAmtTest()
        {
            // TODO unit test for the property 'TotCollAmt'
        }
        /// <summary>
        /// Test the property 'ApplicationType'
        /// </summary>
        [Test]
        public void ApplicationTypeTest()
        {
            // TODO unit test for the property 'ApplicationType'
        }
        /// <summary>
        /// Test the property 'DisbursementMethod'
        /// </summary>
        [Test]
        public void DisbursementMethodTest()
        {
            // TODO unit test for the property 'DisbursementMethod'
        }
        /// <summary>
        /// Test the property 'AnnualIncJoint'
        /// </summary>
        [Test]
        public void AnnualIncJointTest()
        {
            // TODO unit test for the property 'AnnualIncJoint'
        }
        /// <summary>
        /// Test the property 'DtiJoint'
        /// </summary>
        [Test]
        public void DtiJointTest()
        {
            // TODO unit test for the property 'DtiJoint'
        }
        /// <summary>
        /// Test the property 'IsIncVJoint'
        /// </summary>
        [Test]
        public void IsIncVJointTest()
        {
            // TODO unit test for the property 'IsIncVJoint'
        }
        /// <summary>
        /// Test the property 'OpenAcc6m'
        /// </summary>
        [Test]
        public void OpenAcc6mTest()
        {
            // TODO unit test for the property 'OpenAcc6m'
        }
        /// <summary>
        /// Test the property 'OpenIl6m'
        /// </summary>
        [Test]
        public void OpenIl6mTest()
        {
            // TODO unit test for the property 'OpenIl6m'
        }
        /// <summary>
        /// Test the property 'OpenActIl'
        /// </summary>
        [Test]
        public void OpenActIlTest()
        {
            // TODO unit test for the property 'OpenActIl'
        }
        /// <summary>
        /// Test the property 'OpenIl12m'
        /// </summary>
        [Test]
        public void OpenIl12mTest()
        {
            // TODO unit test for the property 'OpenIl12m'
        }
        /// <summary>
        /// Test the property 'OpenIl24m'
        /// </summary>
        [Test]
        public void OpenIl24mTest()
        {
            // TODO unit test for the property 'OpenIl24m'
        }
        /// <summary>
        /// Test the property 'MthsSinceRcntIl'
        /// </summary>
        [Test]
        public void MthsSinceRcntIlTest()
        {
            // TODO unit test for the property 'MthsSinceRcntIl'
        }
        /// <summary>
        /// Test the property 'TotalBalIl'
        /// </summary>
        [Test]
        public void TotalBalIlTest()
        {
            // TODO unit test for the property 'TotalBalIl'
        }
        /// <summary>
        /// Test the property 'ILUtil'
        /// </summary>
        [Test]
        public void ILUtilTest()
        {
            // TODO unit test for the property 'ILUtil'
        }
        /// <summary>
        /// Test the property 'OpenRv12m'
        /// </summary>
        [Test]
        public void OpenRv12mTest()
        {
            // TODO unit test for the property 'OpenRv12m'
        }
        /// <summary>
        /// Test the property 'OpenRv24m'
        /// </summary>
        [Test]
        public void OpenRv24mTest()
        {
            // TODO unit test for the property 'OpenRv24m'
        }
        /// <summary>
        /// Test the property 'MaxBalBc'
        /// </summary>
        [Test]
        public void MaxBalBcTest()
        {
            // TODO unit test for the property 'MaxBalBc'
        }
        /// <summary>
        /// Test the property 'AllUtil'
        /// </summary>
        [Test]
        public void AllUtilTest()
        {
            // TODO unit test for the property 'AllUtil'
        }
        /// <summary>
        /// Test the property 'InqFi'
        /// </summary>
        [Test]
        public void InqFiTest()
        {
            // TODO unit test for the property 'InqFi'
        }
        /// <summary>
        /// Test the property 'TotalCuTl'
        /// </summary>
        [Test]
        public void TotalCuTlTest()
        {
            // TODO unit test for the property 'TotalCuTl'
        }
        /// <summary>
        /// Test the property 'InqLast12m'
        /// </summary>
        [Test]
        public void InqLast12mTest()
        {
            // TODO unit test for the property 'InqLast12m'
        }
        /// <summary>
        /// Test the property 'MtgPayment'
        /// </summary>
        [Test]
        public void MtgPaymentTest()
        {
            // TODO unit test for the property 'MtgPayment'
        }
        /// <summary>
        /// Test the property 'HousingPayment'
        /// </summary>
        [Test]
        public void HousingPaymentTest()
        {
            // TODO unit test for the property 'HousingPayment'
        }
        /// <summary>
        /// Test the property 'RevolBalJoint'
        /// </summary>
        [Test]
        public void RevolBalJointTest()
        {
            // TODO unit test for the property 'RevolBalJoint'
        }
        /// <summary>
        /// Test the property 'SecAppFicoRangeLow'
        /// </summary>
        [Test]
        public void SecAppFicoRangeLowTest()
        {
            // TODO unit test for the property 'SecAppFicoRangeLow'
        }
        /// <summary>
        /// Test the property 'SecAppFicoRangeHigh'
        /// </summary>
        [Test]
        public void SecAppFicoRangeHighTest()
        {
            // TODO unit test for the property 'SecAppFicoRangeHigh'
        }
        /// <summary>
        /// Test the property 'SecAppEarliestCrLine'
        /// </summary>
        [Test]
        public void SecAppEarliestCrLineTest()
        {
            // TODO unit test for the property 'SecAppEarliestCrLine'
        }
        /// <summary>
        /// Test the property 'SecAppInqLast6Mths'
        /// </summary>
        [Test]
        public void SecAppInqLast6MthsTest()
        {
            // TODO unit test for the property 'SecAppInqLast6Mths'
        }
        /// <summary>
        /// Test the property 'SecAppMortAcc'
        /// </summary>
        [Test]
        public void SecAppMortAccTest()
        {
            // TODO unit test for the property 'SecAppMortAcc'
        }
        /// <summary>
        /// Test the property 'SecAppOpenAcc'
        /// </summary>
        [Test]
        public void SecAppOpenAccTest()
        {
            // TODO unit test for the property 'SecAppOpenAcc'
        }
        /// <summary>
        /// Test the property 'SecAppRevolUtil'
        /// </summary>
        [Test]
        public void SecAppRevolUtilTest()
        {
            // TODO unit test for the property 'SecAppRevolUtil'
        }
        /// <summary>
        /// Test the property 'SecAppOpenIl6m'
        /// </summary>
        [Test]
        public void SecAppOpenIl6mTest()
        {
            // TODO unit test for the property 'SecAppOpenIl6m'
        }
        /// <summary>
        /// Test the property 'SecAppOpenActIl'
        /// </summary>
        [Test]
        public void SecAppOpenActIlTest()
        {
            // TODO unit test for the property 'SecAppOpenActIl'
        }
        /// <summary>
        /// Test the property 'SecAppNumRevAccts'
        /// </summary>
        [Test]
        public void SecAppNumRevAcctsTest()
        {
            // TODO unit test for the property 'SecAppNumRevAccts'
        }
        /// <summary>
        /// Test the property 'SecAppChargeoffWithin12Mths'
        /// </summary>
        [Test]
        public void SecAppChargeoffWithin12MthsTest()
        {
            // TODO unit test for the property 'SecAppChargeoffWithin12Mths'
        }
        /// <summary>
        /// Test the property 'SecAppCollections12MthsExMed'
        /// </summary>
        [Test]
        public void SecAppCollections12MthsExMedTest()
        {
            // TODO unit test for the property 'SecAppCollections12MthsExMed'
        }
        /// <summary>
        /// Test the property 'SecAppMthsSinceLastMajorDerog'
        /// </summary>
        [Test]
        public void SecAppMthsSinceLastMajorDerogTest()
        {
            // TODO unit test for the property 'SecAppMthsSinceLastMajorDerog'
        }

    }

}
