/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing NetAnnualizedReturn
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NetAnnualizedReturnTests
    {
        // TODO uncomment below to declare an instance variable for NetAnnualizedReturn
        //private NetAnnualizedReturn instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NetAnnualizedReturn
            //instance = new NetAnnualizedReturn();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NetAnnualizedReturn
        /// </summary>
        [Test]
        public void NetAnnualizedReturnInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NetAnnualizedReturn
            //Assert.IsInstanceOfType<NetAnnualizedReturn> (instance, "variable 'instance' is a NetAnnualizedReturn");
        }


        /// <summary>
        /// Test the property 'PrimaryNAR'
        /// </summary>
        [Test]
        public void PrimaryNARTest()
        {
            // TODO unit test for the property 'PrimaryNAR'
        }
        /// <summary>
        /// Test the property 'PrimaryAdjustedNAR'
        /// </summary>
        [Test]
        public void PrimaryAdjustedNARTest()
        {
            // TODO unit test for the property 'PrimaryAdjustedNAR'
        }
        /// <summary>
        /// Test the property 'PrimaryUserAdjustedNAR'
        /// </summary>
        [Test]
        public void PrimaryUserAdjustedNARTest()
        {
            // TODO unit test for the property 'PrimaryUserAdjustedNAR'
        }
        /// <summary>
        /// Test the property 'TradedNAR'
        /// </summary>
        [Test]
        public void TradedNARTest()
        {
            // TODO unit test for the property 'TradedNAR'
        }
        /// <summary>
        /// Test the property 'TradedAdjustedNAR'
        /// </summary>
        [Test]
        public void TradedAdjustedNARTest()
        {
            // TODO unit test for the property 'TradedAdjustedNAR'
        }
        /// <summary>
        /// Test the property 'TradedUserAdjustedNAR'
        /// </summary>
        [Test]
        public void TradedUserAdjustedNARTest()
        {
            // TODO unit test for the property 'TradedUserAdjustedNAR'
        }
        /// <summary>
        /// Test the property 'CombinedNAR'
        /// </summary>
        [Test]
        public void CombinedNARTest()
        {
            // TODO unit test for the property 'CombinedNAR'
        }
        /// <summary>
        /// Test the property 'CombinedAdjustedNAR'
        /// </summary>
        [Test]
        public void CombinedAdjustedNARTest()
        {
            // TODO unit test for the property 'CombinedAdjustedNAR'
        }
        /// <summary>
        /// Test the property 'CombinedUserAdjustedNAR'
        /// </summary>
        [Test]
        public void CombinedUserAdjustedNARTest()
        {
            // TODO unit test for the property 'CombinedUserAdjustedNAR'
        }

    }

}
