/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing NewOrder
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NewOrderTests
    {
        // TODO uncomment below to declare an instance variable for NewOrder
        //private NewOrder instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NewOrder
            //instance = new NewOrder();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NewOrder
        /// </summary>
        [Test]
        public void NewOrderInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NewOrder
            //Assert.IsInstanceOfType<NewOrder> (instance, "variable 'instance' is a NewOrder");
        }


        /// <summary>
        /// Test the property 'LoadId'
        /// </summary>
        [Test]
        public void LoadIdTest()
        {
            // TODO unit test for the property 'LoadId'
        }
        /// <summary>
        /// Test the property 'RequestedAmount'
        /// </summary>
        [Test]
        public void RequestedAmountTest()
        {
            // TODO unit test for the property 'RequestedAmount'
        }
        /// <summary>
        /// Test the property 'PortfolioId'
        /// </summary>
        [Test]
        public void PortfolioIdTest()
        {
            // TODO unit test for the property 'PortfolioId'
        }

    }

}
