/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Note
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NoteTests
    {
        // TODO uncomment below to declare an instance variable for Note
        //private Note instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Note
            //instance = new Note();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Note
        /// </summary>
        [Test]
        public void NoteInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Note
            //Assert.IsInstanceOfType<Note> (instance, "variable 'instance' is a Note");
        }


        /// <summary>
        /// Test the property 'LoanId'
        /// </summary>
        [Test]
        public void LoanIdTest()
        {
            // TODO unit test for the property 'LoanId'
        }
        /// <summary>
        /// Test the property 'NoteId'
        /// </summary>
        [Test]
        public void NoteIdTest()
        {
            // TODO unit test for the property 'NoteId'
        }
        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Test]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }
        /// <summary>
        /// Test the property 'InterestRate'
        /// </summary>
        [Test]
        public void InterestRateTest()
        {
            // TODO unit test for the property 'InterestRate'
        }
        /// <summary>
        /// Test the property 'LoanLength'
        /// </summary>
        [Test]
        public void LoanLengthTest()
        {
            // TODO unit test for the property 'LoanLength'
        }
        /// <summary>
        /// Test the property 'LoanStatus'
        /// </summary>
        [Test]
        public void LoanStatusTest()
        {
            // TODO unit test for the property 'LoanStatus'
        }
        /// <summary>
        /// Test the property 'Grade'
        /// </summary>
        [Test]
        public void GradeTest()
        {
            // TODO unit test for the property 'Grade'
        }
        /// <summary>
        /// Test the property 'LoanAmount'
        /// </summary>
        [Test]
        public void LoanAmountTest()
        {
            // TODO unit test for the property 'LoanAmount'
        }
        /// <summary>
        /// Test the property 'NoteAmount'
        /// </summary>
        [Test]
        public void NoteAmountTest()
        {
            // TODO unit test for the property 'NoteAmount'
        }
        /// <summary>
        /// Test the property 'PaymentsReceived'
        /// </summary>
        [Test]
        public void PaymentsReceivedTest()
        {
            // TODO unit test for the property 'PaymentsReceived'
        }
        /// <summary>
        /// Test the property 'IssueDate'
        /// </summary>
        [Test]
        public void IssueDateTest()
        {
            // TODO unit test for the property 'IssueDate'
        }
        /// <summary>
        /// Test the property 'OrderDate'
        /// </summary>
        [Test]
        public void OrderDateTest()
        {
            // TODO unit test for the property 'OrderDate'
        }
        /// <summary>
        /// Test the property 'LoanStatusDate'
        /// </summary>
        [Test]
        public void LoanStatusDateTest()
        {
            // TODO unit test for the property 'LoanStatusDate'
        }

    }

}
