/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PortfoliosOwned
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PortfoliosOwnedTests
    {
        // TODO uncomment below to declare an instance variable for PortfoliosOwned
        //private PortfoliosOwned instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PortfoliosOwned
            //instance = new PortfoliosOwned();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PortfoliosOwned
        /// </summary>
        [Test]
        public void PortfoliosOwnedInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PortfoliosOwned
            //Assert.IsInstanceOfType<PortfoliosOwned> (instance, "variable 'instance' is a PortfoliosOwned");
        }


        /// <summary>
        /// Test the property 'MyPortfolios'
        /// </summary>
        [Test]
        public void MyPortfoliosTest()
        {
            // TODO unit test for the property 'MyPortfolios'
        }

    }

}
