/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ScheduledTransfer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ScheduledTransferTests
    {
        // TODO uncomment below to declare an instance variable for ScheduledTransfer
        //private ScheduledTransfer instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ScheduledTransfer
            //instance = new ScheduledTransfer();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ScheduledTransfer
        /// </summary>
        [Test]
        public void ScheduledTransferInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ScheduledTransfer
            //Assert.IsInstanceOfType<ScheduledTransfer> (instance, "variable 'instance' is a ScheduledTransfer");
        }


        /// <summary>
        /// Test the property 'InvestorId'
        /// </summary>
        [Test]
        public void InvestorIdTest()
        {
            // TODO unit test for the property 'InvestorId'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'TransferFrequency'
        /// </summary>
        [Test]
        public void TransferFrequencyTest()
        {
            // TODO unit test for the property 'TransferFrequency'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Test]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'EstimatedFundsTransferDate'
        /// </summary>
        [Test]
        public void EstimatedFundsTransferDateTest()
        {
            // TODO unit test for the property 'EstimatedFundsTransferDate'
        }

    }

}
