/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SellNoteExecutionStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SellNoteExecutionStatusTests
    {
        // TODO uncomment below to declare an instance variable for SellNoteExecutionStatus
        //private SellNoteExecutionStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SellNoteExecutionStatus
            //instance = new SellNoteExecutionStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SellNoteExecutionStatus
        /// </summary>
        [Test]
        public void SellNoteExecutionStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SellNoteExecutionStatus
            //Assert.IsInstanceOfType<SellNoteExecutionStatus> (instance, "variable 'instance' is a SellNoteExecutionStatus");
        }



    }

}
