/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SellNotesStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SellNotesStatusTests
    {
        // TODO uncomment below to declare an instance variable for SellNotesStatus
        //private SellNotesStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SellNotesStatus
            //instance = new SellNotesStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SellNotesStatus
        /// </summary>
        [Test]
        public void SellNotesStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SellNotesStatus
            //Assert.IsInstanceOfType<SellNotesStatus> (instance, "variable 'instance' is a SellNotesStatus");
        }



    }

}
