/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SellNote
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SellNoteTests
    {
        // TODO uncomment below to declare an instance variable for SellNote
        //private SellNote instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SellNote
            //instance = new SellNote();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SellNote
        /// </summary>
        [Test]
        public void SellNoteInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SellNote
            //Assert.IsInstanceOfType<SellNote> (instance, "variable 'instance' is a SellNote");
        }


        /// <summary>
        /// Test the property 'LoanId'
        /// </summary>
        [Test]
        public void LoanIdTest()
        {
            // TODO unit test for the property 'LoanId'
        }
        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Test]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }
        /// <summary>
        /// Test the property 'NoteId'
        /// </summary>
        [Test]
        public void NoteIdTest()
        {
            // TODO unit test for the property 'NoteId'
        }
        /// <summary>
        /// Test the property 'AskingPrice'
        /// </summary>
        [Test]
        public void AskingPriceTest()
        {
            // TODO unit test for the property 'AskingPrice'
        }
        /// <summary>
        /// Test the property 'ExecutionStatus'
        /// </summary>
        [Test]
        public void ExecutionStatusTest()
        {
            // TODO unit test for the property 'ExecutionStatus'
        }

    }

}
