/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SubmitOrderResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SubmitOrderResponseTests
    {
        // TODO uncomment below to declare an instance variable for SubmitOrderResponse
        //private SubmitOrderResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SubmitOrderResponse
            //instance = new SubmitOrderResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SubmitOrderResponse
        /// </summary>
        [Test]
        public void SubmitOrderResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SubmitOrderResponse
            //Assert.IsInstanceOfType<SubmitOrderResponse> (instance, "variable 'instance' is a SubmitOrderResponse");
        }


        /// <summary>
        /// Test the property 'OrderInstructId'
        /// </summary>
        [Test]
        public void OrderInstructIdTest()
        {
            // TODO unit test for the property 'OrderInstructId'
        }
        /// <summary>
        /// Test the property 'OrderConfirmations'
        /// </summary>
        [Test]
        public void OrderConfirmationsTest()
        {
            // TODO unit test for the property 'OrderConfirmations'
        }

    }

}
