/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Transfer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TransferTests
    {
        // TODO uncomment below to declare an instance variable for Transfer
        //private Transfer instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Transfer
            //instance = new Transfer();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Transfer
        /// </summary>
        [Test]
        public void TransferInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Transfer
            //Assert.IsInstanceOfType<Transfer> (instance, "variable 'instance' is a Transfer");
        }


        /// <summary>
        /// Test the property 'TransferId'
        /// </summary>
        [Test]
        public void TransferIdTest()
        {
            // TODO unit test for the property 'TransferId'
        }
        /// <summary>
        /// Test the property 'TransferDate'
        /// </summary>
        [Test]
        public void TransferDateTest()
        {
            // TODO unit test for the property 'TransferDate'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'SourceAccount'
        /// </summary>
        [Test]
        public void SourceAccountTest()
        {
            // TODO unit test for the property 'SourceAccount'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Frequency'
        /// </summary>
        [Test]
        public void FrequencyTest()
        {
            // TODO unit test for the property 'Frequency'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Test]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'Operation'
        /// </summary>
        [Test]
        public void OperationTest()
        {
            // TODO unit test for the property 'Operation'
        }
        /// <summary>
        /// Test the property 'Cancellable'
        /// </summary>
        [Test]
        public void CancellableTest()
        {
            // TODO unit test for the property 'Cancellable'
        }

    }

}
