/* 
 * Lending Club API
 *
 * Lending Club API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILoansApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filterId"> (optional)</param>
        /// <param name="showAll"> (optional)</param>
        /// <param name="X_LC_LISTING_VERSION"> (optional)</param>
        /// <returns>ListedLoans</returns>
        ListedLoans ListedLoans (int? filterId = null, bool? showAll = null, string X_LC_LISTING_VERSION = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filterId"> (optional)</param>
        /// <param name="showAll"> (optional)</param>
        /// <param name="X_LC_LISTING_VERSION"> (optional)</param>
        /// <returns>ApiResponse of ListedLoans</returns>
        ApiResponse<ListedLoans> ListedLoansWithHttpInfo (int? filterId = null, bool? showAll = null, string X_LC_LISTING_VERSION = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filterId"> (optional)</param>
        /// <param name="showAll"> (optional)</param>
        /// <param name="X_LC_LISTING_VERSION"> (optional)</param>
        /// <returns>Task of ListedLoans</returns>
        System.Threading.Tasks.Task<ListedLoans> ListedLoansAsync (int? filterId = null, bool? showAll = null, string X_LC_LISTING_VERSION = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filterId"> (optional)</param>
        /// <param name="showAll"> (optional)</param>
        /// <param name="X_LC_LISTING_VERSION"> (optional)</param>
        /// <returns>Task of ApiResponse (ListedLoans)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListedLoans>> ListedLoansAsyncWithHttpInfo (int? filterId = null, bool? showAll = null, string X_LC_LISTING_VERSION = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class LoansApi : ILoansApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="LoansApi"/> class.
        /// </summary>
        /// <returns></returns>
        public LoansApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LoansApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public LoansApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filterId"> (optional)</param>
        /// <param name="showAll"> (optional)</param>
        /// <param name="X_LC_LISTING_VERSION"> (optional)</param>
        /// <returns>ListedLoans</returns>
        public ListedLoans ListedLoans (int? filterId = null, bool? showAll = null, string X_LC_LISTING_VERSION = null)
        {
             ApiResponse<ListedLoans> localVarResponse = ListedLoansWithHttpInfo(filterId, showAll, X_LC_LISTING_VERSION);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filterId"> (optional)</param>
        /// <param name="showAll"> (optional)</param>
        /// <param name="X_LC_LISTING_VERSION"> (optional)</param>
        /// <returns>ApiResponse of ListedLoans</returns>
        public ApiResponse< ListedLoans > ListedLoansWithHttpInfo (int? filterId = null, bool? showAll = null, string X_LC_LISTING_VERSION = null)
        {

            var localVarPath = "/loans/listing";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (filterId != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "filterId", filterId)); // query parameter
            if (showAll != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "showAll", showAll)); // query parameter
            if (X_LC_LISTING_VERSION != null) localVarHeaderParams.Add("X-LC-LISTING-VERSION", Configuration.ApiClient.ParameterToString(X_LC_LISTING_VERSION)); // header parameter

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ListedLoans", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ListedLoans>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ListedLoans) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ListedLoans)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filterId"> (optional)</param>
        /// <param name="showAll"> (optional)</param>
        /// <param name="X_LC_LISTING_VERSION"> (optional)</param>
        /// <returns>Task of ListedLoans</returns>
        public async System.Threading.Tasks.Task<ListedLoans> ListedLoansAsync (int? filterId = null, bool? showAll = null, string X_LC_LISTING_VERSION = null)
        {
             ApiResponse<ListedLoans> localVarResponse = await ListedLoansAsyncWithHttpInfo(filterId, showAll, X_LC_LISTING_VERSION);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filterId"> (optional)</param>
        /// <param name="showAll"> (optional)</param>
        /// <param name="X_LC_LISTING_VERSION"> (optional)</param>
        /// <returns>Task of ApiResponse (ListedLoans)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ListedLoans>> ListedLoansAsyncWithHttpInfo (int? filterId = null, bool? showAll = null, string X_LC_LISTING_VERSION = null)
        {

            var localVarPath = "/loans/listing";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (filterId != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "filterId", filterId)); // query parameter
            if (showAll != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "showAll", showAll)); // query parameter
            if (X_LC_LISTING_VERSION != null) localVarHeaderParams.Add("X-LC-LISTING-VERSION", Configuration.ApiClient.ParameterToString(X_LC_LISTING_VERSION)); // header parameter

            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ListedLoans", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ListedLoans>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ListedLoans) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ListedLoans)));
        }

    }
}
